### PR TITLE
Properly hide trail when there are no parents

### PR DESCRIPTION
**Pull request by chrisgrieser**
right now, it still leaves an empty table there

### CODE REVIEW

**Comment by SkepticMystic** [comment]
Thanks for the PR!
What do you mean in your comment?
> right no, it still leaves an empty table there

**Comment by chrisgrieser** [comment]
image
this one is still displayed when there are no parents. the added CSS removes that :)

**Comment by SkepticMystic** [comment]
Ohhhhh, the spelling error made me think you where saying "Right, no, my PR doesn't actually solve the issue" 😋 
Thanks! Merged :)

**Comment by chrisgrieser** [comment]
haha, yes, I fixed it :D

**Pull request merged**
