### PR TITLE
Obsi v0.15 compatibility

### PR DESCRIPTION
**Pull request by kometenstaub**
I did a search and replace for `getActiveFile` and replaced it with a function.

I accidentally commited main.js and yarn.lock. I removed them with a rebase.

I only checked it with the matrix view because that is the only one I use, but I replaced everything and it should work.

`lastActiveFile` seems to be a private API. I suppose you want a clean history so I'll just leave this as a draft PR for now, also because of the private API. It's probably better to wait until a public API is made available.

### CODE REVIEW

**Comment by kometenstaub** [comment]
@kometenstaub You probably shouldn't use `active-leaf-change` but instead `file-open`, as it will only fire for opened files and not every pane that can get focus.

And `lastActiveFile` should also not be used. (something else will probably be made public)

**Comment by SkepticMystic** [comment]
@kometenstaub I'm testing it out now. Everything seems to work so far!
Why do you say not to use `lastActiveFile`? Do you know what I should be using instead?

**Comment by kometenstaub** [comment]
Probably `getMostRecetlyActiveFile` will be made public.

But in any case, you should use the file-open event instead of active-leaf-change, because then `getActiveFile` should continue working in this context. Only where a view doesn't rely on the event, should you use a either `getActiveFile` or `getMostRecentlyActiveFile`/both combined (I didn't test the new API behaviour yet).

**Comment by SkepticMystic** [comment]
Oh ok, so the two are related. If I switch to `file-open`, then I can keep using `getActiveFile`?

**Comment by kometenstaub** [comment]
Yes.

**Comment by SkepticMystic** [comment]
Thank you. Everything seems to work, gonna merge it now.

Btw, here is a simpler version of the function you wrote, just in case you help someone else with this, too :)

```js
export const getCurrFile = (): TFile | null => app.workspace.getActiveFile() ?? app.workspace.getMostRecentlyActiveFile()
```

**Comment by kometenstaub** [comment]
Thanks, I wasn't aware of this format. I usually go with longer functions, because I find them more easily understandable.

**Pull request merged**
